### ISSUE TITLE
[BUG] ARM generates aliases which aren't followed by the "unused label" filter

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#1799]
Consider the code: https://godbolt.org/z/_tHcS2  - note how the `sg_days` table isn't present (nor is it directly referenced in the asm output, in fairness).

The `sg_days` table is double-indirected through an anchor (`.LANCHOR0`). The `.LANCHOR0` isn't a label, but it is instead an alias to sg_days. If you turn off the `.text` you'll see:

```asm
        .set    .LANCHOR0,. + 0
        .type   sg_days, %object
        .size   sg_days, 48
sg_days:
        .word   31
        .word   28
        .word   31
        .word   30
        .word   31
        .word   30
...
```

I'm not sure how best to show this. If we have directive filtering on, then the fact that `sg_days` == `.LANCHOR0` is not clear; so just including `sg_days` in the output is not enough. Ideas welcomed.

**Comment by OfekShilon** [comment]
@mattgodbolt  I *think* this is fixed by #5706. `sg_days` label and content are visible in assembly.

**Comment by mattgodbolt** [comment]
I accidentally linked the wrong link : https://godbolt.org/z/axYGjjWar exhibits the problem still. (the original link had the filters turned off) with "directive filter" we only see:

```as
DaysInMonth2():
        ldr     r3, .L8
        ldr     r3, [r3]
        ldr     r2, .L8+4
        cmp     r3, #1
        ldr     r2, [r2]
        beq     .L7
.L2:
        ldr     r2, .L8+8
        ldr     r0, [r2, r3, lsl #2]
        bx      lr
.L7:
        tst     r2, #3
        bne     .L2
        ldr     r1, .L8+12
        smull   ip, r0, r1, r2
        asr     r1, r2, #31
        rsb     r1, r1, r0, asr #3
        add     r1, r1, r1, lsl #2
        add     r1, r1, r1, lsl #2
        cmp     r2, r1
        bne     .L5
        tst     r2, #15
        bne     .L2
.L5:
        mov     r0, #29
        bx      lr
.L8:
        .word   b
        .word   a
        .word   .LANCHOR0
        .word   1374389535
```

With the "directive filter" off, then among all the noise is the part we'd like to see:

```as
        .set    .LANCHOR0,. + 0
        .type   sg_days, %object
        .size   sg_days, 48
sg_days:
        .word   31
        .word   28
        .word   31
        .word   30
        .word   31
        .word   30
        .word   31
        .word   31
        .word   30
        .word   31
        .word   30
        .word   31
        .text
```
