### ISSUE TITLE
[BUG] The font in the "Add tool..." drop-down list became strange 

### ISSUE THREAD

**Issue by GeorgeGribkov** [compiler-explorer/compiler-explorer#2029]
**Describe the bug**
The font in the "Add tool..." drop-down list is weird now

**To Reproduce**
Open a compiler window, click the "Add tool..." button and see that the font is strange.

**Expected behavior**
The font should be the same as in other dropdowns and it should fit the borders.

**Link**
https://godbolt.org/z/BcrSDt

**Screenshots**
![image](https://user-images.githubusercontent.com/59817335/84643422-77a22100-af06-11ea-956c-6d1ff5930fb7.png)

**Desktop:**
 - OS: Windows
 - Browser: Chrome, Firefox, and maybe others

**Comment by RabsRincon** [comment]
Thanks! For the record, the overflow was first fixed in e215d8f31f6a83430d365b21ed6ac23d5f15f2d7 (Reported in #2027) but when fixing this I found a better way for both issues - Thanks!

**Comment by GeorgeGribkov** [comment]
Thank you too, Rabs!

**Comment by GeorgeGribkov** [comment]
It's strange, but the bug is still present on our machines. How long does it take for a change to take effect?

**Comment by apmorton** [comment]
The fix has been applied on the master branch, but the site has not been deployed since then (which is a manual process).

**Comment by GeorgeGribkov** [comment]
Oh. How often do you deploy? I just need to make some gifs for an article about using PVS-Studio in CE, but I want these gifs to be pretty =D

**Comment by apmorton** [comment]
I have deployed the latest build now

**Comment by GeorgeGribkov** [comment]
Thank you very much!
