### ISSUE TITLE
[BUG]: armv7-a clang: #include <stdio.h> may lead to fatal error: 'stdio.h' file not found

### ISSUE THREAD

**Issue by pmor13** [compiler-explorer/compiler-explorer#4094]
### Describe the bug

armv7-a clang: `#include <stdio.h>` may lead to `fatal error: 'stdio.h' file not found`.

### Steps to reproduce

```
#include <stdio.h>
```

### Expected behavior

The 'stdio.h' file is found.

### Reproduction link

https://godbolt.org/z/4befzv8oq

**Comment by pmor13** [comment]
It starts with armv7-a clang 12.0.0.

**Comment by partouf** [comment]
They were recently added in a PR, but I now notice they are using the wrong gcc toolchain paths, hence the not finding the c headers. The compilers were also not added to C++.

We'll have to go through them 1 by 1 and fix all the paths manually.

**Comment by partouf** [comment]
Fixed in https://github.com/compiler-explorer/compiler-explorer/commit/f22a2a3a782a22e820ae57f3daa755c55347fbd0 (not live yet)
Still need to add to c++

**Comment by jeremy-rifkin** [comment]
It looks like the error is still happening on trunk, is that intentional?

**Comment by partouf** [comment]
I think at some point we fixed it, but then it another bug was filed that we were using the wrong target architecture. So basically clang arm is a unknown mess now

**Comment by partouf** [comment]
ah and https://github.com/compiler-explorer/compiler-explorer/commit/f22a2a3a782a22e820ae57f3daa755c55347fbd0 only applied to specific versions

**Comment by partouf** [comment]
So sort of related to https://github.com/compiler-explorer/compiler-explorer/issues/3868

**Comment by arichardson** [comment]
It appears I need to pass `--gcc-install-dir=/opt/compiler-explorer/arm/gcc-12.2.0/arm-unknown-linux-gnueabihf/lib/gcc/arm-unknown-linux-gnueabihf/12.2.0 --sysroot=/opt/compiler-explorer/arm/gcc-12.2.0/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/` to get anything C++ to work for armv7-a clang.

**Comment by mattgodbolt** [comment]
Thanks all!
